# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=256)),
                ('imagen', s3direct.fields.S3DirectField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('cupo', models.IntegerField()),
                ('asistentes', models.IntegerField(default=0)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=256)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Categoria')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disponible',
            fields=[
                ('estadoevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.EstadoEvento')),
            ],
            bases=('evento.estadoevento',),
        ),
        migrations.CreateModel(
            name='Lleno',
            fields=[
                ('estadoevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.EstadoEvento')),
            ],
            bases=('evento.estadoevento',),
        ),
        migrations.CreateModel(
            name='Pagada',
            fields=[
                ('estadoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.EstadoEntrada')),
            ],
            bases=('evento.estadoentrada',),
        ),
        migrations.CreateModel(
            name='SinPagar',
            fields=[
                ('estadoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.EstadoEntrada')),
            ],
            bases=('evento.estadoentrada',),
        ),
        migrations.CreateModel(
            name='Terminado',
            fields=[
                ('estadoevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.EstadoEvento')),
            ],
            bases=('evento.estadoevento',),
        ),
        migrations.CreateModel(
            name='Validada',
            fields=[
                ('estadoentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.EstadoEntrada')),
            ],
            bases=('evento.estadoentrada',),
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EstadoEvento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.TipoEvento'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.EstadoEntrada'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
