# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20170710_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='ciudad',
            new_name='provincia',
        ),
    ]
