# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20170710_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
