# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_evento_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnVivo',
            fields=[
                ('estadoevento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.EstadoEvento')),
            ],
            bases=('evento.estadoevento',),
        ),
    ]
