# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_envivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
