# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_auto_20170822_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
