# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerial',
            fields=[
                ('plan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pay.Plan')),
            ],
            bases=('pay.plan',),
        ),
        migrations.RenameModel(
            old_name='Free',
            new_name='Gratis',
        ),
    ]
