# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20170711_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cost',
            field=models.FloatField(default=100),
        ),
    ]
