# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_plan_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='id_mp',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
