# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_auto_20171106_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='suscripto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='days',
            field=models.IntegerField(default=32),
        ),
    ]
