# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20170709_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
