# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_vendidos',
            field=models.IntegerField(default=0),
        ),
    ]
