# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_cantidad_vendidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.EstadoCompra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
