# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_producto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
