# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 02:16
from __future__ import unicode_literals

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
