# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-21 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20170721_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='token',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
