# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20170721_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
