# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_auto_20170724_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='url_envio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
