# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_auto_20170724_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
