# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('imagen', s3direct.fields.S3DirectField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
