# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('accounts', '0002_auto_20170627_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
        ),
    ]
