# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='customer_id_mp',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
