# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_customer_id_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='receive_newsletter',
            field=models.BooleanField(default=True, verbose_name='receive newsletter'),
        ),
    ]
